/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dougl
 */
public class Exemplos extends javax.swing.JFrame {

    /**
     * Creates new form Exemplos
     */
    public Exemplos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbcExemplos = new javax.swing.JTabbedPane();
        pnlPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlDesvios = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        pnlLacos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        pnlDeclaracoes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        pnlFuncoes = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        pnlOperadores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbcExemplos.setToolTipText("");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("//Contém a definição inicial do programa\nstatic void main(){\n//Comentários simples\n\n/* Comentários múltiplos */\n\n}");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        tbcExemplos.addTab("Principal", pnlPrincipal);

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("if(a > b){\n...\n}\n\nif(a > b){\n...\n}else{\n...\n}\n\nif(a > b){\n\n}else if(e == d){\n\n}\n\n");
        jScrollPane7.setViewportView(jTextArea7);

        javax.swing.GroupLayout pnlDesviosLayout = new javax.swing.GroupLayout(pnlDesvios);
        pnlDesvios.setLayout(pnlDesviosLayout);
        pnlDesviosLayout.setHorizontalGroup(
            pnlDesviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        pnlDesviosLayout.setVerticalGroup(
            pnlDesviosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        tbcExemplos.addTab("Desvios ", pnlDesvios);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("for(int i=0;i<10;i++){\n}\n\nforeach(string s in t){\n}\n\nwhile(a > b){\n}\n\ndo{\n}while(a < 10);");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout pnlLacosLayout = new javax.swing.GroupLayout(pnlLacos);
        pnlLacos.setLayout(pnlLacosLayout);
        pnlLacosLayout.setHorizontalGroup(
            pnlLacosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        pnlLacosLayout.setVerticalGroup(
            pnlLacosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        tbcExemplos.addTab("Laços", pnlLacos);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("//Número inteiros\nint i;\nint i = 10;\n\n//Números decimais\ndouble d;\ndouble d = 9.6;\n\n//Strings\nstring s;\nstring s = \"Olá Mundo!\";\n\n//Char\nchar c;\nchar c = 'u';\n\n//Boleanos\nbool b;\nbool b = true;\n\n//Vetores\nint[] veti = new vet[10];\nstring[] vets = new vets[2];\nchar vetc = new vetc[9];\nbool vetb = new vetb[7];");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout pnlDeclaracoesLayout = new javax.swing.GroupLayout(pnlDeclaracoes);
        pnlDeclaracoes.setLayout(pnlDeclaracoesLayout);
        pnlDeclaracoesLayout.setHorizontalGroup(
            pnlDeclaracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        pnlDeclaracoesLayout.setVerticalGroup(
            pnlDeclaracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        tbcExemplos.addTab("Declaração", pnlDeclaracoes);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("private void teste1(){\n\tint teste = 0;\n\tdouble t = 1.9;\n\tstring s = \"s\";\n\tchar c = 'a';\n}\n\npublic void teste2(){\n\tint teste = 0;\n\tdouble t = 1.9;\n\tstring s = \"s\";\n\tchar c = 'a';\n}\n\nprotected void teste3(){\n\tint teste = 0;\n\tdouble t = 1.9;\n\tstring s = \"s\";\n\tchar c = 'a';\n}\n\nvoid teste4(){\n\tint teste = 0;\n\tdouble t = 1.9;\n\tstring s = \"s\";\n\t//char c = 'a';\n\tchar z;\n\tint i = 2;\n}\n\nprivate int teste5(){\n\tint teste = 0;\n\tdouble t = 1.9;\n\tstring s = \"s\";\n\tchar c = 'a';\n}\n\nprivate double teste6(){\n\tint teste = 0;\n\tdouble t = 1.9;\n\tstring s = \"s\";\n\tchar c = 'a';\n}\n\nprivate string teste7(){\n\tint teste = 0;\n\tdouble t = 1.9;\n\tstring s = \"s\";\n\tchar c = 'a';\n}\n\nprivate char teste8(){\n\tint teste = 0;\n\tdouble t = 1.9;\n\tstring s = \"s\";\n\tchar c = 'a';\n}\n\nprivate int teste9(){\n\tint teste = 0;\n\tdouble t = 1.9;\n\tstring s = \"s\";\n\tchar c = 'a';\n}\n\nprivate int teste9(string teste, int p, char c){\n\tint teste = 0;\n\tdouble t = 1.9;\n\tstring s = \"s\";\n\tchar c = 'a';\n}");
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout pnlFuncoesLayout = new javax.swing.GroupLayout(pnlFuncoes);
        pnlFuncoes.setLayout(pnlFuncoesLayout);
        pnlFuncoesLayout.setHorizontalGroup(
            pnlFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        pnlFuncoesLayout.setVerticalGroup(
            pnlFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        tbcExemplos.addTab("Funções", pnlFuncoes);

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("//Saída de dados\nWrite(\"Teste\");\n\n//Entrada de dados\nRead(\"Teste 1\");");
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        tbcExemplos.addTab("I/O", jPanel1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("a + b;\t//Adição\nb - 10;\t//Subtração\nx * 3 ;\t//Multiplicação\ny / 10;\t//Divisão\n10 % 5;\t//Mod\n\na++;\t//Incrementa\ni--;\t//Decrementa\n\n>= \t//Maior igual\n<=\t//Menor igual\n==\t//Igual\n!= \t//Diferente\n\n\n>> \t//Right bit\n<<\t//Left bit\n\n\n");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout pnlOperadoresLayout = new javax.swing.GroupLayout(pnlOperadores);
        pnlOperadores.setLayout(pnlOperadoresLayout);
        pnlOperadoresLayout.setHorizontalGroup(
            pnlOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        pnlOperadoresLayout.setVerticalGroup(
            pnlOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        tbcExemplos.addTab("Operadores", pnlOperadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbcExemplos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbcExemplos)
        );

        tbcExemplos.getAccessibleContext().setAccessibleName("tbpInicio");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JPanel pnlDeclaracoes;
    private javax.swing.JPanel pnlDesvios;
    private javax.swing.JPanel pnlFuncoes;
    private javax.swing.JPanel pnlLacos;
    private javax.swing.JPanel pnlOperadores;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTabbedPane tbcExemplos;
    // End of variables declaration//GEN-END:variables
}
